### ISSUE TITLE
Error: Can't resolve 'level-js'

### ISSUE THREAD

**Issue by Simoneth** [FileNation/FileNation#75]
Hi,
I git cloned the project on my Win 8.1 x64 and after `npm i`
this error was generated:
```
ERROR in ./node_modules/ipfs-repo/src/default-options-browser.js
Module not found: Error: Can't resolve 'level-js' in 'C:\projects\snapcloud\node
_modules\ipfs-repo\src'
 @ ./node_modules/ipfs-repo/src/default-options-browser.js 14:10-29 19:10-29 23:
10-29 26:10-29
 @ ./node_modules/ipfs-repo/src/index.js
 @ ./node_modules/ipfs/src/core/runtime/repo-browser.js
 @ ./node_modules/ipfs/src/core/index.js
 @ ./src/app/ipfs.service.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./node_modules/libp2p-crypto/src/webcrypto.js
Module not found: Error: Can't resolve 'webcrypto-shim' in 'C:\projects\snapclou
d\node_modules\libp2p-crypto\src'
 @ ./node_modules/libp2p-crypto/src/webcrypto.js 8:4-29
 @ ./node_modules/libp2p-crypto/src/hmac/index-browser.js
 @ ./node_modules/libp2p-crypto/src/index.js
 @ ./node_modules/peer-id/src/index.js
 @ ./node_modules/ipfs/src/core/index.js
 @ ./src/app/ipfs.service.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./node_modules/libp2p-webrtc-star/src/index.js
Module not found: Error: Can't resolve 'webrtcsupport' in 'C:\projects\snapcloud
\node_modules\libp2p-webrtc-star\src'
 @ ./node_modules/libp2p-webrtc-star/src/index.js 16:22-46
 @ ./node_modules/ipfs/src/core/runtime/libp2p-browser.js
 @ ./node_modules/ipfs/src/core/components/libp2p.js
 @ ./node_modules/ipfs/src/core/components/index.js
 @ ./node_modules/ipfs/src/core/index.js
 @ ./src/app/ipfs.service.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./node_modules/bittorrent-protocol/index.js
Module not found: Error: Can't resolve 'xtend' in 'C:\projects\snapcloud\node_mo
dules\bittorrent-protocol'
 @ ./node_modules/bittorrent-protocol/index.js 8:13-29
 @ ./node_modules/webtorrent/lib/peer.js
 @ ./node_modules/webtorrent/lib/torrent.js
 @ ./node_modules/webtorrent/index.js
 @ ./src/app/ipfs.service.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./node_modules/bittorrent-tracker/client.js
Module not found: Error: Can't resolve 'xtend' in 'C:\projects\snapcloud\node_mo
dules\bittorrent-tracker'
 @ ./node_modules/bittorrent-tracker/client.js 6:13-29
 @ ./node_modules/torrent-discovery/index.js
 @ ./node_modules/webtorrent/lib/torrent.js
 @ ./node_modules/webtorrent/index.js
 @ ./src/app/ipfs.service.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./node_modules/bittorrent-tracker/lib/client/websocket-tracker.js
Module not found: Error: Can't resolve 'xtend' in 'C:\projects\snapcloud\node_mo
dules\bittorrent-tracker\lib\client'
 @ ./node_modules/bittorrent-tracker/lib/client/websocket-tracker.js 4:13-29
 @ ./node_modules/bittorrent-tracker/client.js
 @ ./node_modules/torrent-discovery/index.js
 @ ./node_modules/webtorrent/lib/torrent.js
 @ ./node_modules/webtorrent/index.js
 @ ./src/app/ipfs.service.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./node_modules/create-torrent/index.js
Module not found: Error: Can't resolve 'xtend' in 'C:\projects\snapcloud\node_mo
dules\create-torrent'
 @ ./node_modules/create-torrent/index.js 19:13-29
 @ ./node_modules/webtorrent/index.js
 @ ./src/app/ipfs.service.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./node_modules/deferred-leveldown/node_modules/abstract-leveldown/abstr
act-leveldown.js
Module not found: Error: Can't resolve 'xtend' in 'C:\projects\snapcloud\node_mo
dules\deferred-leveldown\node_modules\abstract-leveldown'
 @ ./node_modules/deferred-leveldown/node_modules/abstract-leveldown/abstract-le
veldown.js 3:27-43
 @ ./node_modules/deferred-leveldown/node_modules/abstract-leveldown/index.js
 @ ./node_modules/deferred-leveldown/deferred-leveldown.js
 @ ./node_modules/levelup/lib/levelup.js
 @ ./node_modules/datastore-level/src/index.js
 @ ./node_modules/ipfs-repo/src/default-options-browser.js
 @ ./node_modules/ipfs-repo/src/index.js
 @ ./node_modules/ipfs/src/core/runtime/repo-browser.js
 @ ./node_modules/ipfs/src/core/index.js
 @ ./src/app/ipfs.service.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./node_modules/level-iterator-stream/index.js
Module not found: Error: Can't resolve 'xtend' in 'C:\projects\snapcloud\node_mo
dules\level-iterator-stream'
 @ ./node_modules/level-iterator-stream/index.js 3:13-29
 @ ./node_modules/levelup/lib/levelup.js
 @ ./node_modules/datastore-level/src/index.js
 @ ./node_modules/ipfs-repo/src/default-options-browser.js
 @ ./node_modules/ipfs-repo/src/index.js
 @ ./node_modules/ipfs/src/core/runtime/repo-browser.js
 @ ./node_modules/ipfs/src/core/index.js
 @ ./src/app/ipfs.service.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./node_modules/levelup/lib/levelup.js
Module not found: Error: Can't resolve 'xtend' in 'C:\projects\snapcloud\node_mo
dules\levelup\lib'
 @ ./node_modules/levelup/lib/levelup.js 10:13-29
 @ ./node_modules/datastore-level/src/index.js
 @ ./node_modules/ipfs-repo/src/default-options-browser.js
 @ ./node_modules/ipfs-repo/src/index.js
 @ ./node_modules/ipfs/src/core/runtime/repo-browser.js
 @ ./node_modules/ipfs/src/core/index.js
 @ ./src/app/ipfs.service.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./node_modules/magnet-uri/index.js
Module not found: Error: Can't resolve 'xtend' in 'C:\projects\snapcloud\node_mo
dules\magnet-uri'
 @ ./node_modules/magnet-uri/index.js 7:13-29
 @ ./node_modules/parse-torrent/index.js
 @ ./node_modules/webtorrent/lib/torrent.js
 @ ./node_modules/webtorrent/index.js
 @ ./src/app/ipfs.service.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./node_modules/multiaddr/src/index.js
Module not found: Error: Can't resolve 'xtend' in 'C:\projects\snapcloud\node_mo
dules\multiaddr\src'
 @ ./node_modules/multiaddr/src/index.js 4:15-31
 @ ./node_modules/ipfs/src/core/index.js
 @ ./src/app/ipfs.service.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./node_modules/stream-http/index.js
Module not found: Error: Can't resolve 'xtend' in 'C:\projects\snapcloud\node_mo
dules\stream-http'
 @ ./node_modules/stream-http/index.js 2:13-29
 @ ./node_modules/webtorrent/node_modules/simple-get/index.js
 @ ./node_modules/webtorrent/lib/webconn.js
 @ ./node_modules/webtorrent/lib/peer.js
 @ ./node_modules/webtorrent/lib/torrent.js
 @ ./node_modules/webtorrent/index.js
 @ ./src/app/ipfs.service.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./node_modules/torrent-discovery/index.js
Module not found: Error: Can't resolve 'xtend' in 'C:\projects\snapcloud\node_mo
dules\torrent-discovery'
 @ ./node_modules/torrent-discovery/index.js 6:13-29
 @ ./node_modules/webtorrent/lib/torrent.js
 @ ./node_modules/webtorrent/index.js
 @ ./src/app/ipfs.service.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./node_modules/webtorrent/index.js
Module not found: Error: Can't resolve 'xtend' in 'C:\projects\snapcloud\node_mo
dules\webtorrent'
 @ ./node_modules/webtorrent/index.js 11:13-29
 @ ./src/app/ipfs.service.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./node_modules/webtorrent/lib/torrent.js
Module not found: Error: Can't resolve 'xtend' in 'C:\projects\snapcloud\node_mo
dules\webtorrent\lib'
 @ ./node_modules/webtorrent/lib/torrent.js 11:13-29
 @ ./node_modules/webtorrent/index.js
 @ ./src/app/ipfs.service.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./node_modules/bittorrent-tracker/lib/common.js
Module not found: Error: Can't resolve 'xtend/mutable' in 'C:\projects\snapcloud
\node_modules\bittorrent-tracker\lib'
 @ ./node_modules/bittorrent-tracker/lib/common.js 6:13-37
 @ ./node_modules/bittorrent-tracker/client.js
 @ ./node_modules/torrent-discovery/index.js
 @ ./node_modules/webtorrent/lib/torrent.js
 @ ./node_modules/webtorrent/index.js
 @ ./src/app/ipfs.service.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./node_modules/webtorrent/lib/torrent.js
Module not found: Error: Can't resolve 'xtend/mutable' in 'C:\projects\snapcloud
\node_modules\webtorrent\lib'
 @ ./node_modules/webtorrent/lib/torrent.js 12:20-44
 @ ./node_modules/webtorrent/index.js
 @ ./src/app/ipfs.service.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://localhost:4200 ./src/main.ts
Child html-webpack-plugin for "index.html":
     1 asset
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html] ./node_m
odules/html-webpack-plugin/lib/loader.js!./src/index.html 1.51 kB {0} [built]
webpack: Failed to compile.
```

**Comment by Simoneth** [comment]
Anyone please?

**Comment by alexsicart** [comment]
The problem should be solved with the last update! Say me if works! :) @Simoneth

**Comment by Simoneth** [comment]
@alexsicart thanks,
I tried again, however this is the output:
```
s\npm\node_modules\node-gyp\lib\configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:197:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\projects\Filenation\node_modules\secp256k1
gyp ERR! node -v v8.0.0
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! secp256k1@3.4.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the secp256k1@3.4.0 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to in
stall?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\simon\AppData\Roaming\npm-cache\_logs\2017-12-24T16_23_05_
445Z-debug.log
"Secp256k1 bindings compilation fail. Pure JS implementation will be used."

> node-sass@4.7.2 install C:\projects\Filenation\node_modules\node-sass
> node scripts/install.js

module.js:487
    throw err;
    ^

Error: Cannot find module 'xtend'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\projects\Filenation\node_modules\is-my-json-valid\
index.js:4:13)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)

> leveldown@1.9.0 install C:\projects\Filenation\node_modules\leveldown
> prebuild-install || node-gyp rebuild

module.js:487
    throw err;
    ^

Error: Cannot find module 'xtend'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\projects\Filenation\node_modules\prebuild-install\
bin.js:6:14)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)

C:\projects\Filenation\node_modules\leveldown>if not defined npm_config_node_gyp
 (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_mo
dules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
  builder.cc
  db_impl.cc
  db_iter.cc
  filename.cc
  dbformat.cc
  log_reader.cc
  log_writer.cc
  memtable.cc
  repair.cc
  table_cache.cc
  version_edit.cc
C:\projects\Filenation\node_modules\leveldown\deps\leveldb\leveldb-1.20\db/skip
list.h(360): warning C4312: 'reinterpret_cast': conversion from 'int' to 'void
*' of greater size (compiling source file leveldb-1.20\db\memtable.cc) [C:\proj
ects\Filenation\node_modules\leveldown\deps\leveldb\leveldb.vcxproj]
  C:\projects\Filenation\node_modules\leveldown\deps\leveldb\leveldb-1.20\db/sk
  iplist.h(337): note: while compiling class template member function 'void lev
  eldb::SkipList<const char *,leveldb::MemTable::KeyComparator>::Insert(const K
  ey &)'
          with
          [
              Key=const char *
          ] (compiling source file leveldb-1.20\db\memtable.cc)
  leveldb-1.20\db\memtable.cc(105): note: see reference to function template in
  stantiation 'void leveldb::SkipList<const char *,leveldb::MemTable::KeyCompar
  ator>::Insert(const Key &)' being compiled
          with
          [
              Key=const char *
          ]
  C:\projects\Filenation\node_modules\leveldown\deps\leveldb\leveldb-1.20\db/me
  mtable.h(79): note: see reference to class template instantiation 'leveldb::S
  kipList<const char *,leveldb::MemTable::KeyComparator>' being compiled (compi
  ling source file leveldb-1.20\db\memtable.cc)
  version_set.cc
  write_batch.cc
  memenv.cc
  port_posix_sse.cc
  block.cc
  block_builder.cc
  filter_block.cc
  format.cc
  iterator.cc
  merger.cc
  table.cc
  table_builder.cc
  two_level_iterator.cc
  arena.cc
  bloom.cc
  cache.cc
  coding.cc
  comparator.cc
  crc32c.cc
  env.cc
  filter_policy.cc
  hash.cc
  logging.cc
  options.cc
  status.cc
  port_uv.cc
  env_win.cc
  win_logger.cc
  win_delay_load_hook.cc
  leveldb.vcxproj -> C:\projects\Filenation\node_modules\leveldown\build\Releas
  e\\leveldb.lib
  snappy-sinksource.cc
  snappy-stubs-internal.cc
  snappy.cc
  win_delay_load_hook.cc
  snappy.vcxproj -> C:\projects\Filenation\node_modules\leveldown\build\Release
  \\snappy.lib
  batch.cc
  batch_async.cc
  database.cc
  database_async.cc
  iterator.cc
  iterator_async.cc
  leveldown.cc
  leveldown_async.cc
  win_delay_load_hook.cc
     Creating library C:\projects\Filenation\node_modules\leveldown\build\Relea
  se\leveldown.lib and object C:\projects\Filenation\node_modules\leveldown\bui
  ld\Release\leveldown.exp
  Generating code
  Finished generating code
  leveldown.vcxproj -> C:\projects\Filenation\node_modules\leveldown\build\Rele
  ase\\leveldown.node
  leveldown.vcxproj -> C:\projects\Filenation\node_modules\leveldown\build\Rele
  ase\leveldown.pdb (Full PDB)

> keccak@1.4.0 install C:\projects\Filenation\node_modules\keccak
> npm run rebuild || echo "Keccak bindings compilation fail. Pure JS implementat
ion will be used."


> keccak@1.4.0 rebuild C:\projects\Filenation\node_modules\keccak
> node-gyp rebuild


C:\projects\Filenation\node_modules\keccak>if not defined npm_config_node_gyp (n
ode "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modul
es\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
module.js:487
    throw err;
    ^

Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at [eval]:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:44:33)
    at Object.runInThisContext (vm.js:116:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:569:30)
    at evalScript (bootstrap_node.js:432:27)
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.
gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_module
s\npm\node_modules\node-gyp\lib\configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:197:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\projects\Filenation\node_modules\keccak
gyp ERR! node -v v8.0.0
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keccak@1.4.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keccak@1.4.0 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to in
stall?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\simon\AppData\Roaming\npm-cache\_logs\2017-12-24T16_23_38_
569Z-debug.log
"Keccak bindings compilation fail. Pure JS implementation will be used."

> gc-stats@1.1.0 install C:\projects\Filenation\node_modules\gc-stats
> node-pre-gyp install --fallback-to-build

[gc-stats] Success: "C:\projects\Filenation\node_modules\gc-stats\build\gcstats\
v1.1.0\Release\node-v57-win32-x64\gcstats.node" is installed via remote

> fsevents@1.1.2 install C:\projects\Filenation\node_modules\fsevents
> node install


> bufferutil@3.0.3 install C:\projects\Filenation\node_modules\bufferutil
> prebuild-install || node-gyp rebuild

module.js:487
    throw err;
    ^

Error: Cannot find module 'xtend'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\projects\Filenation\node_modules\prebuild-install\
bin.js:6:14)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)

```
