### ISSUE TITLE
Error: Cannot find module 'debug' | portfinder

### ISSUE THREAD

**Issue by Simoneth** [FileNation/FileNation#82]
Hi,
Again I can't get it works, this time is portfinder
```
Error: Cannot find module 'debug'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\progetti\Filenation\node_modules\portfinder\lib\portfinder.js:15:13)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Filenation@0.0.0 start: `webpack-dev-server --port=4200`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Filenation@0.0.0 start script.
```
I already tried rm node_modules folder; npm cache clear --force; npm install;
But again the same error

Specs:
Node JS v. 8.0.0
NPM v. 5.0.0
Windows 8.1 64bit

**Comment by Simoneth** [comment]
Anyway I removed portfinder from package.json and it seems to work now.
